title: Proyecto Final
lang: es
description: Proyecto Final DI 2024
remote_theme: rundocs/dark-poole

plugins:
  
jemoji
jekyll-avatar
jekyll-mentions
jekyll-feed
jekyll-include-cache
jekyll-remote-theme